"""Compatibility imports for core-owned stable role identifiers."""

from agent_factory_core.organizations.system_roles import (
    MEMBER_ROLE_ID,
    ORGANIZATION_ADMIN_ROLE_ID,
    ORGANIZATION_MEMBER_ROLE_ID,
    ORGANIZATION_OWNER_ROLE_ID,
    PLATFORM_ADMIN_ROLE_ID,
    VIEWER_ROLE_ID,
    WORKSPACE_ADMIN_ROLE_ID,
    WORKSPACE_OWNER_ROLE_ID,
)

__all__ = [
    "MEMBER_ROLE_ID",
    "ORGANIZATION_ADMIN_ROLE_ID",
    "ORGANIZATION_MEMBER_ROLE_ID",
    "ORGANIZATION_OWNER_ROLE_ID",
    "PLATFORM_ADMIN_ROLE_ID",
    "VIEWER_ROLE_ID",
    "WORKSPACE_ADMIN_ROLE_ID",
    "WORKSPACE_OWNER_ROLE_ID",
]
