from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from .domain import (
    AgentDefinition,
    AgentRun,
    AgentVersion,
    RunArtifact,
    RunDocumentLink,
    RunEvent,
    RunToolCall,
)


class AgentRepository(Protocol):
    async def lock_workspace(self, organization_id: UUID, workspace_id: UUID) -> bool: ...
    async def list_definitions(self, workspace_id: UUID) -> list[AgentDefinition]: ...
    async def get_definition(
        self, workspace_id: UUID, definition_id: UUID, *, lock: bool = False
    ) -> AgentDefinition | None: ...
    async def insert_definition(self, value: AgentDefinition) -> AgentDefinition: ...
    async def replace_definition(
        self, value: AgentDefinition, expected_revision: int
    ) -> AgentDefinition | None: ...
    async def soft_delete_definition(
        self, workspace_id: UUID, definition_id: UUID, expected_revision: int, now: datetime
    ) -> bool: ...
    async def list_versions(
        self, workspace_id: UUID, definition_id: UUID
    ) -> list[AgentVersion]: ...
    async def get_version(
        self, workspace_id: UUID, definition_id: UUID, version_id: UUID | None
    ) -> AgentVersion | None: ...
    async def insert_version(
        self, definition: AgentDefinition, value: AgentVersion
    ) -> AgentVersion: ...
    async def list_runs(self, workspace_id: UUID, limit: int = 100) -> list[AgentRun]: ...
    async def get_run(
        self, workspace_id: UUID, run_id: UUID, *, lock: bool = False
    ) -> AgentRun | None: ...
    async def find_run(self, workspace_id: UUID, idempotency_key: str) -> AgentRun | None: ...
    async def insert_run(self, value: AgentRun) -> AgentRun: ...
    async def replace_run(self, value: AgentRun) -> AgentRun: ...
    async def append_event(
        self, run: AgentRun, event_type: str, payload: dict[str, object]
    ) -> RunEvent: ...
    async def list_events(self, workspace_id: UUID, run_id: UUID) -> list[RunEvent]: ...
    async def list_tool_calls(self, workspace_id: UUID, run_id: UUID) -> list[RunToolCall]: ...
    async def list_artifacts(self, workspace_id: UUID, run_id: UUID) -> list[RunArtifact]: ...
    async def list_document_links(
        self, workspace_id: UUID, run_id: UUID
    ) -> list[RunDocumentLink]: ...
    async def insert_tool_call(self, value: RunToolCall) -> RunToolCall: ...
    async def insert_artifact(self, value: RunArtifact) -> RunArtifact: ...
    async def insert_document_link(self, value: RunDocumentLink) -> RunDocumentLink: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


class AgentJobPublisher(Protocol):
    async def stage(self, run: AgentRun) -> object: ...
    def publish(self, job: object) -> str: ...
    async def record_publication(self, job: object, publication_id: str) -> None: ...
    async def cancel(self, run: AgentRun) -> None: ...


class AgentWorkspaceLookup(Protocol):
    async def organization_id(self, workspace_id: UUID) -> UUID | None: ...
