from __future__ import annotations

from typing import Protocol
from uuid import UUID

from .domain import PlanItem, PlanSettings


class PlanningRepository(Protocol):
    async def lock_workspace(self, organization_id: UUID, workspace_id: UUID) -> bool: ...
    async def list_items(self, workspace_id: UUID) -> list[PlanItem]: ...
    async def get_item(self, workspace_id: UUID, item_id: UUID) -> PlanItem | None: ...
    async def insert_item(self, item: PlanItem) -> PlanItem: ...
    async def replace_item(self, item: PlanItem, expected_revision: int) -> PlanItem | None: ...
    async def delete_item(
        self, workspace_id: UUID, item_id: UUID, expected_revision: int
    ) -> bool: ...
    async def has_linked_report(self, workspace_id: UUID, item_id: UUID) -> bool: ...
    async def get_settings(self, workspace_id: UUID) -> PlanSettings | None: ...
    async def save_settings(
        self, settings: PlanSettings, expected_revision: int
    ) -> PlanSettings | None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class HolidayCalendar(Protocol):
    def holidays(self, dates: list[object]) -> dict[str, str]: ...
