"""Ports required by identity and authentication use cases."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from .domain import (
    ApiTokenRecord,
    CredentialRecord,
    PasswordLoginRecord,
    ResolvedApiToken,
    SessionRecord,
    UserRecord,
)


class Clock(Protocol):
    def now(self) -> datetime: ...


class IdentityCrypto(Protocol):
    def hash_password(self, password: str) -> str: ...
    def verify_password(self, password: str, encoded: str | None) -> tuple[bool, str | None]: ...
    def new_opaque_token(self) -> str: ...
    def token_digest(self, token: str) -> bytes: ...


class IdentityRepository(Protocol):
    async def find_password_login(self, normalized_email: str) -> PasswordLoginRecord | None: ...
    async def find_user_by_email(self, normalized_email: str) -> UserRecord | None: ...
    async def find_user_by_id(self, user_id: UUID) -> UserRecord | None: ...
    async def record_failed_login(
        self, credential: CredentialRecord, *, locked_until: datetime | None
    ) -> None: ...
    async def record_successful_login(
        self, credential: CredentialRecord, updated_password_hash: str | None
    ) -> None: ...
    async def create_session(
        self, *, user_id: UUID, digest: bytes, expires_at: datetime, user_agent: str | None
    ) -> SessionRecord: ...
    async def find_or_create_external_user(
        self, *, provider: str, subject: str, normalized_email: str, display_name: str
    ) -> UserRecord: ...
    async def resolve_session(self, digest: bytes, now: datetime) -> UserRecord | None: ...
    async def revoke_session(self, digest: bytes, now: datetime) -> None: ...
    async def list_sessions(self, user_id: UUID) -> list[SessionRecord]: ...
    async def revoke_session_by_id(
        self, user_id: UUID, session_id: UUID, now: datetime
    ) -> None: ...
    async def create_api_token(
        self,
        *,
        user_id: UUID,
        name: str,
        digest: bytes,
        scopes: list[str],
        expires_at: datetime | None,
    ) -> ApiTokenRecord: ...
    async def add_mcp_connection(
        self, *, user_id: UUID, organization_id: UUID, workspace_id: UUID, token_id: UUID, name: str
    ) -> None: ...
    async def list_api_tokens(self, user_id: UUID) -> list[ApiTokenRecord]: ...
    async def resolve_api_token(self, digest: bytes, now: datetime) -> ResolvedApiToken | None: ...
    async def revoke_api_token(self, user_id: UUID, token_id: UUID, now: datetime) -> None: ...
    async def create_one_time_token(
        self, *, user_id: UUID, purpose: str, digest: bytes, expires_at: datetime
    ) -> None: ...
    async def consume_one_time_token(
        self, *, purpose: str, digest: bytes, now: datetime
    ) -> UserRecord | None: ...
    async def mark_email_verified(self, user: UserRecord, now: datetime) -> None: ...
    async def replace_password(
        self, user: UserRecord, password_hash: str, now: datetime
    ) -> None: ...
    async def commit(self) -> None: ...
