from __future__ import annotations

from collections.abc import Awaitable, Callable
from contextlib import AbstractAsyncContextManager
from datetime import datetime
from typing import Protocol, Self
from uuid import UUID

from agent_factory_core.identity.authorization import AuthorizedContext

from .domain import Job, JobEvent, Schedule


class SchedulingRepository(Protocol):
    async def control_plane_job(self, job_id: UUID) -> Job | None: ...
    async def list_schedules(self, workspace_id: UUID) -> list[Schedule]: ...
    async def get_schedule(
        self, workspace_id: UUID, schedule_id: UUID, *, lock: bool = False
    ) -> Schedule | None: ...
    async def insert_schedule(self, schedule: Schedule) -> Schedule: ...
    async def replace_schedule(
        self, schedule: Schedule, expected_revision: int
    ) -> Schedule | None: ...
    async def delete_schedule(
        self, workspace_id: UUID, schedule_id: UUID, expected_revision: int
    ) -> bool: ...
    async def find_job(self, workspace_id: UUID, idempotency_key: str) -> Job | None: ...
    async def insert_job(self, job: Job) -> Job: ...
    async def get_job(
        self, workspace_id: UUID, job_id: UUID, *, lock: bool = False
    ) -> Job | None: ...
    async def list_jobs(self, workspace_id: UUID, limit: int = 100) -> list[Job]: ...
    async def replace_job(self, job: Job) -> Job: ...
    async def append_event(
        self, job: Job, event_type: str, payload: dict[str, object]
    ) -> JobEvent: ...
    async def list_events(self, workspace_id: UUID, job_id: UUID) -> list[JobEvent]: ...
    async def due_schedules(self, now: datetime, limit: int = 100) -> list[Schedule]: ...
    async def due_dispatches(
        self, now: datetime, stale_before: datetime, limit: int = 100
    ) -> list[Job]: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class JobPublisher(Protocol):
    def publish(self, job: Job, *, countdown: int = 0) -> str: ...


class Handler(Protocol):
    async def __call__(
        self,
        job: Job,
        context: AuthorizedContext,
        cancelled: Callable[[], Awaitable[bool]],
    ) -> dict[str, object]: ...


class ExecutionAuthorizer(Protocol):
    async def authorize(self, job: Job) -> AuthorizedContext: ...


class ExecutionLease(Protocol):
    job: Job
    repository: SchedulingRepository

    async def establish(self, context: AuthorizedContext) -> None: ...
    async def establish_durable_identity(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type: object, exc: object, traceback: object) -> None: ...


class ExecutionLeaseFactory(Protocol):
    async def acquire(self, job_id: UUID) -> AbstractAsyncContextManager[ExecutionLease] | None: ...


class JobLifecycle(Protocol):
    async def finalized(self, job: Job, context: AuthorizedContext | None) -> None: ...
