import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, relative, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath, URL } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaRoot = resolve(root, "contracts/schemas");
const output = resolve(root, "packages/contracts-ts/src/generated/validators.js");
const declarationOutput = resolve(root, "packages/contracts-ts/src/generated/validators.d.ts");
const require = createRequire(new URL("../packages/contracts-ts/package.json", import.meta.url));
const Ajv2020 = require("ajv/dist/2020").default;
const standaloneCode = require("ajv/dist/standalone").default;

function files(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(directory, entry.name);
    return entry.isDirectory() ? files(path) : entry.name.endsWith(".json") ? [path] : [];
  });
}

const schemaEntries = files(schemaRoot)
  .sort()
  .map((path, index) => ({
    path: `schemas/${relative(schemaRoot, path).replaceAll("\\", "/")}`,
    schema: JSON.parse(readFileSync(path, "utf8")),
    exportName: `validateContract${index}`,
  }));
const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  allowUnionTypes: true,
  schemas: schemaEntries.map(({ schema }) => schema),
  code: { source: true, esm: true, lines: true },
});
const exports = Object.fromEntries(schemaEntries.map(({ exportName, schema }) => [exportName, schema.$id]));
const validators = schemaEntries.map(({ path, exportName }) => `  ${JSON.stringify(path)}: ${exportName},`).join("\n");
const runtimeImports = [];
const compiled = standaloneCode(ajv, exports).replace(
  /const (func\d+) = require\("([^"]+)"\)\.default;\n/g,
  (_, name, module) => {
    runtimeImports.push(`import ${name} from ${JSON.stringify(`${module}.js`)};`);
    return "";
  },
);
const generated = `// Generated by scripts/generate_workbench_validators.mjs; do not edit.\n${runtimeImports.join(
  "\n",
)}\n${compiled}\nexport const validators = Object.freeze({\n${validators}\n});\n`;
const declaration = `// Generated by scripts/generate_workbench_validators.mjs; do not edit.\nimport type { ErrorObject } from "ajv";\n\nexport interface ContractValidator {\n  (document: unknown): boolean;\n  errors?: ErrorObject[] | null;\n}\n\nexport const validators: Readonly<Record<string, ContractValidator>>;\n`;

const check = process.argv.includes("--check");
for (const [path, content] of [
  [output, generated],
  [declarationOutput, declaration],
]) {
  if (check) {
    if (readFileSync(path, "utf8") !== content) throw new Error(`generated validator differs: ${relative(root, path)}`);
  } else {
    writeFileSync(path, content);
  }
}
