from __future__ import annotations

from collections.abc import Mapping
from typing import Protocol

from agent_factory_core.identity import Principal

from .domain import Dashboard, FeatureFlag


class PlatformAdministrationRepository(Protocol):
    async def authorize_and_establish(self, principal: Principal) -> bool: ...
    async def dashboard(self) -> Dashboard: ...
    async def list_flags(self, *, limit: int) -> list[FeatureFlag]: ...
    async def set_flag(
        self, *, key: str, enabled: bool, description: str, rules: Mapping[str, object]
    ) -> FeatureFlag: ...
    async def migration_version(self) -> str | None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class RuntimeInformation(Protocol):
    @property
    def application_version(self) -> str: ...
    @property
    def environment(self) -> str: ...
    @property
    def debug(self) -> bool: ...
    @property
    def embedding_provider(self) -> str: ...
