from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from typing import Protocol
from uuid import UUID

from .domain import Provider, ProviderConnection


class ProviderConnectionRepository(Protocol):
    def guard(
        self, workspace_id: UUID, connection_id: UUID
    ) -> AbstractAsyncContextManager[None]: ...
    async def lock_workspace(self, organization_id: UUID, workspace_id: UUID) -> bool: ...
    async def providers(self) -> list[Provider]: ...
    async def provider(self, provider_id: UUID) -> Provider | None: ...
    async def connections(self, workspace_id: UUID) -> list[ProviderConnection]: ...
    async def insert_connection(
        self,
        value: ProviderConnection,
        encrypted_credentials: bytes | None,
        key_version: int | None,
    ) -> ProviderConnection: ...
    async def disconnect(
        self, workspace_id: UUID, connection_id: UUID
    ) -> ProviderConnection | None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class SecretCipher(Protocol):
    @property
    def key_version(self) -> int: ...
    def encrypt(self, value: dict[str, object]) -> bytes: ...
